# Generated by Django 4.0.4 on 2022-08-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=250)),
                ('medicine_image', models.ImageField(blank=True, null=True, upload_to='products')),
                ('medicine_price', models.IntegerField()),
                ('medicine_descripton', models.TextField()),
                ('medicine_exp', models.DateField()),
            ],
        ),
    ]
