# Generated by Django 4.0.4 on 2022-08-06 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_medicines'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicines',
            old_name='medicine_image',
            new_name='medicinei',
        ),
    ]
