# Generated by Django 4.0.4 on 2022-08-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_medicines'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='products')),
                ('price', models.IntegerField()),
                ('exp', models.DateField()),
            ],
        ),
    ]
