# Generated by Django 4.0.4 on 2023-01-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_medicines'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=250)),
                ('prod_image', models.ImageField(blank=True, null=True, upload_to='products')),
                ('prod_price', models.IntegerField()),
                ('prod_descripton', models.TextField()),
                ('prod_exp', models.DateField()),
            ],
        ),
    ]
